Merge clause PR
opencypher/openCypher pull request #450
Opened 2020-09-30 08:44 UTC by DvirDukhan

2020-09-30 09:13 UTC, DvirDukhan reviewed
@hvub
here are some renaming suggestions for this PR

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/clauses/merge/Merge1.feature
> +  Scenario: Should support updates while merging
```suggestion
  Scenario: Merge should support updates while merging
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/clauses/merge/Merge1.feature
> +  Scenario: Introduce named paths 2
```suggestion
  Scenario: Merge a node in a named path
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/clauses/merge/Merge3.feature
> +  Scenario: Should be able to set labels on match
```suggestion
  Scenario: Merge should be able to set labels on match
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/clauses/merge/Merge4.feature
> +  Scenario: Should be able to set labels on match and on create
```suggestion
  Scenario: Merge should be able to set labels on match and on create
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/precategorized/clauses/merge/Merge1-1.feature
> +  Scenario: Should be able to merge using property from match
```suggestion
  Scenario: Merge should be able to merge using property from match
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/precategorized/clauses/merge/Merge1-1.feature
> +  Scenario: Should be able to use properties from match in ON MATCH
```suggestion
  Scenario: Merge should be able to use properties from match in ON MATCH
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/precategorized/clauses/merge/Merge1-1.feature
> +  Scenario: Should be able to use properties from match in ON MATCH and ON CREATE
```suggestion
  Scenario: Merge should be able to use properties from match in ON MATCH and ON CREATE
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/precategorized/clauses/merge/Merge1-2.feature
> +  Scenario: Should handle arguments properly with only write clauses
```suggestion
  Scenario: Merge should handle arguments properly with only write clauses
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/precategorized/clauses/merge/Merge1-2.feature
> +  Scenario: Should be able to use properties from match in ON CREATE
```suggestion
  Scenario: Merge should be able to use properties from match in ON CREATE
```

2020-09-30 09:13 UTC, DvirDukhan commented on tck/features/clauses/merge/Merge5.feature
>    Scenario: Introduce named paths 1
```suggestion
  Scenario: Merge entities in named path
```

2020-10-06 09:33 UTC, hvub requested changes
Generally this looks pretty good, I think. I have made a couple of suggestions.

Mainly, I suggest to be a little more proactive with scenarios that combine `MERGE` with other clauses. It is not necessarily exactly what we did so far, but maybe a semi-consistent concept of how deal with these interoperability scenarios can arise from that in the following weeks.

Specifically my thinking is, scenarios that test whether `MERGE` does or does not do something based variables that other clauses have bound or delete before seems to be clearly testing functionality of `MERGE`.

I have not made similar suggestion for `UNWIND` before `MERGE` – I am/was still unsure about it – although, I now realize, it fits the description given about. Probably, we should be adventurous and move these `UNWIND` before `MERGE` scenarios into the appropriate `MergeX.feature` files, as well.

I saw one scenario that does `CREATE` + `MERGE` + `CREATE`. That is less clear, so I am pretty sure it should stay in pre-categorized for now.

@DvirDukhan If you could make the adjustments and add the numbering, please. I will then have a final look. Thx.

2020-10-07 20:51 UTC, hvub approved these changes
Assuming the inclusion of the little suggestion about the missing space, this look good and can be merged.

2020-10-07 20:51 UTC, hvub commented on tck/features/precategorized/clauses/merge/Merge2-2.feature
> +  Scenario: [1]UNWIND with multiple merges
```suggestion
  Scenario: [1] UNWIND with multiple merges
```
space missing.

2020-10-08 07:12 UTC, merged