return clause - first commit
opencypher/openCypher pull request #465
Opened 2020-11-25 22:24 UTC by DvirDukhan

Modifications:
renamed scenarios:
Return3 - Returning an expression --> Returning multiple expressions

Return4 - To the relevant scenarios, I removed `Background` and added 
```
    Given an empty graph
    And having executed:
      """
      CREATE ()
      """
```

Still wondering how to treat the remaining scenarios in `ReturnAcceptance2` as they contain a mixture of projection clauses (`WITH`, `RETURN`)

2020-12-08 08:46 UTC, hvub requested changes
This review mainly looks into getting the build green and addressing some naming issues, I have seen along the way.

In summary, the build failed since some features got accidentally made invalid. Easy to fix. 

I still have to look into the actual categorization. Let's get these build troubles out of the way first.

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return/Return2.feature
> +      | ({numbers: [1, 2, 3]})
```suggestion
      | ({numbers: [1, 2, 3]}) |
    And no side effects
```

Should fix cucumber parsing problem and InvalidFeatureFormatException during build.

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-skip-limit/Return-Skip_Limit2.feature
> +  Scenario: Handle ORDER BY with LIMIT 1
```suggestion
  Scenario: Handle ORDER BY with LIMIT 1
    Given an empty graph
```

should fix InvalidFeatureFormatException

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-skip-limit/Return-Skip_Limit2.feature
> +  Scenario: ORDER BY with LIMIT 0 should not generate errors
```suggestion
  Scenario: ORDER BY with LIMIT 0 should not generate errors
    Given any graph
```
should fix InvalidFeatureFormatException

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-skip-limit/Return-Skip_Limit2.feature
> +Feature: Return-Skip-Limit 2 - Limit
```suggestion
Feature: ReturnSkipLimit2 - Limit

```

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-skip-limit/Return-Skip_Limit1.feature
> +
Please rename the file to `ReturnSkipLimit1.feature` (hyphen instead of underscore)

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-skip-limit/Return-Skip_Limit1.feature
> +Feature: Return-Skip-Limit 1 - Skip
```suggestion
Feature: ReturnSkipLimit1 - Skip

```

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-skip-limit/Return-Skip_Limit2.feature
> +
Please rename the file to `ReturnSkipLimit2.feature` (hyphen instead of underscore)

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-skip-limit/Return-Skip_Limit3.feature
> +
Please rename the file to `ReturnSkipLimit3.feature` (hyphen instead of underscore)

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-skip-limit/Return-Skip_Limit3.feature
> +Feature: Return-Skip-Limit 2 - Skip & limit
```suggestion
Feature: ReturnSkipLimit3 - Skip and limit
```

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby2.feature
> +    Given an empty graph
```suggestion
```
Should fix InvalidFeatureFormatException

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby2.feature
> +  Scenario: ORDER BY should return results in ascending order
```suggestion
  Scenario: ORDER BY should return results in ascending order
    Given an empty graph
```
Should fix InvalidFeatureFormatException

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby2.feature
> +  Scenario: ORDER BY DESC should return results in descending order
```suggestion
  Scenario: ORDER BY DESC should return results in descending order
    Given an empty graph
```
Should fix InvalidFeatureFormatException

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby5.feature
> +  Scenario: Renaming columns before ORDER BY should return results in ascending order
```suggestion
  Scenario: Renaming columns before ORDER BY should return results in ascending order
    Given an empty graph
```
Should fix InvalidFeatureFormatException

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby5.feature
> +Feature: Return-Order By 5 - Order by in combination with column renaming
```suggestion
Feature: ReturnOrderBy5 - Order by in combination with column renaming
```
For consistency. In `MatchWhereX` and  `WithWhereX` we also have not used hyphens on the feature name.

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby1.feature
> +Feature: Return-Order By 1 - Order by a single variable (correct order of values according to their type)
```suggestion
Feature: ReturnOrderBy1 - Order by a single variable (correct order of values according to their type)
```
For consistency. In `MatchWhereX` and  `WithWhereX` we also have not used hyphens or spaces on the feature name.

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby1.feature
> +
Please rename file to `ReturnOrderBy1.feature`

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby2.feature
> +
Please rename file to `ReturnOrderBy2.feature`

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby2.feature
> +Feature: Return-Order By 2 - Order by a single expression (order of projection)
```suggestion
Feature: ReturnOrderBy2 - Order by a single expression (order of projection)
```

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby3.feature
> +
Please rename file to `ReturnOrderBy3.feature`

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby3.feature
> +Feature: Return-Order By 3 - Order by multiple expressions (order obey priority of expressions)
```suggestion
Feature: ReturnOrderBy3 - Order by multiple expressions (order obey priority of expressions)
```

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby4.feature
> +
Please rename file to `ReturnOrderBy4.feature`

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby4.feature
> +Feature: Return-Order By 4 - Order by in combination with projection
```suggestion
Feature: ReturnOrderBy4 - Order by in combination with projection
```

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby4.feature
> +
```suggestion
```

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby4.feature
> +  Scenario: ORDER BY of a column introduced in RETURN should return salient results in ascending order
```suggestion
  Scenario: ORDER BY of a column introduced in RETURN should return salient results in ascending order
    Given an empty graph
```

2020-12-08 08:46 UTC, hvub commented on tck/features/clauses/return-orderby/Return-Orderby4.feature
> +  Scenario: Handle projections with ORDER BY - GH#4937
```suggestion
  Scenario: Handle projections with ORDER BY
    Given an empty graph
```

2020-12-15 12:27 UTC, hvub requested changes
I left a couple of simple change requests. Nothing wild.

When 

* these changes are done and 
* the numbering is added,

this should be ready to go in. :-)

2020-12-15 12:27 UTC, hvub commented on tck/features/clauses/return/Return5.feature
> +    And no side effects
That should go to `With5`. Apparently an oversight on my part. ;-)

2020-12-22 09:31 UTC, DvirDukhan commented on tck/features/clauses/return/Return1.feature
> +  Scenario: Arithmetic expressions should propagate null values
yep

2020-12-22 10:05 UTC, merged