Update procedure CIP
opencypher/openCypher pull request #484
Opened 2021-02-19 10:26 UTC by Lojjs

2021-02-19 12:51 UTC, Hunterness commented on cip/1.accepted/CIP2015-06-24-call-procedures.adoc
>  The `YIELD *` form is _only_ allowed in the standalone form of `CALL`.
This might be redundant

2021-02-19 12:51 UTC, Hunterness commented on cip/1.accepted/CIP2015-06-24-call-procedures.adoc
> +==== Standalone call with omitted `YIELD` clause
This and the section on line 207 feels a bit repetitive, especially directly after each other

2021-02-19 12:51 UTC, Hunterness commented on cip/1.accepted/CIP2015-06-24-call-procedures.adoc
> +==== Standalone call with omitted `YIELD` clause
This section should be part of standalone call section? Not on the same level?

2021-02-25 08:11 UTC, Mats-SX requested changes
I had some minor suggestions for typos and clarity.

2021-02-25 08:11 UTC, Mats-SX commented on cip/1.accepted/CIP2015-06-24-call-procedures.adoc
> +For procedure that does not return any result fields, the query will return as many (empty) rows as produced by the called procedure.
```suggestion
For a procedure that does not return any result fields, the query will return as many (empty) rows as produced by the called procedure.
```

2021-02-25 08:11 UTC, Mats-SX commented on cip/1.accepted/CIP2015-06-24-call-procedures.adoc
> +For procedure that does not return any result fields, the query will return as many (empty) rows as produced by the called procedure.
```suggestion
For a procedure that does not return any result fields, the query will return as many (empty) rows as produced by the called procedure.
```

2021-02-25 08:11 UTC, Mats-SX commented on cip/1.accepted/CIP2015-06-24-call-procedures.adoc
> +Another subclause allowed in the standalone form is `YIELD *`, which denotes that all result fields produced by the procedure implementation are returned by the statement.
```suggestion
A special argument `*` (star) may be given to the `YIELD` subclause in the standalone form.
This denotes that all result fields produced by the procedure implementation are returned by the statement.
```

2021-02-25 08:11 UTC, Mats-SX commented on cip/1.accepted/CIP2015-06-24-call-procedures.adoc
> +As a further simplification, the `YIELD` subcluase can be omitted alltogether from a standalone procedure call, leading to an even more concise syntax:
```suggestion
As a further simplification, the `YIELD` subclause can be omitted altogether in a standalone procedure call, leading to an even more concise syntax:
```

2021-02-25 13:26 UTC, Hunterness approved these changes

2021-02-26 08:10 UTC, Mats-SX approved these changes

2021-03-10 07:27 UTC, merged