Support expected errors with side effects
opencypher/openCypher pull request #548
Opened 2022-10-18 10:20 UTC by loveleif

Enables asserting side effects in failing queries. This is useful for `CALL ... IN TRANSACTIONS` queries, that will fail but also have side effects.

2022-10-20 13:14 UTC, hvub requested changes
The changes make sense in principle. However, from the scenario syntax point of view it is not obvious why additional syntax is needed. This seems to be only done because the steps are processed one-by-one `CypherTCK.toScenario`. 

I would rather prefer that a scenario does not have to ", with side effects:", because "Then an Error should be ... And the side effects should be. ..." already says this sufficiently. 

In `CypherTCK.toScenario` such scenarios can be detected by a one step look ahead. The look ahead can be implement, for example, by replacing 

```scala
val steps = pickle.getSteps.asScala.flatMap { step =>
```

with

```scala
    val stepsAsScala = pickle.getSteps.asScala.toSeq
    val successorSteps = stepsAsScala.tail.map(Some(_)) :+ None
    val stepsAsScalaWithSuccessor = stepsAsScala.zip(successorSteps)

    val steps = stepsAsScalaWithSuccessor.flatMap { case (step, successorStep) =>
```

then `successorStep` can be used to decide in `case expectErrorR(errorType, time, detail) => ...` whether to generate a `SideEffects(source = step).fillInZeros` or not.

I think, that given us a cleaner scenario syntax.

2022-10-20 16:54 UTC, loveleif commented
> I would rather prefer that a scenario does not have to ", with side effects:", because "Then an Error should be ... And the side effects should be. ..." already says this sufficiently.

@hvub smart! I also didn't like it but didn't thought about that possibility, thanks!

2022-10-20 19:00 UTC, loveleif commented
Forced pushed an improved solution to this branch.

2023-03-14 09:51 UTC, hvub approved these changes

2023-03-14 09:58 UTC, hvub commented
I have looked at this again — commit to do the requested change myself — and found that it is not needed. 

Since `insertSideEffectsOnExpectError` sets the `source` of the inserted `SideEffects` steps to the `source` of the preceding `ExpectError` step and `ExpectError` steps always come with `StepType.THEN`, the inserted `SideEffects` steps fit the check in: 
https://github.com/opencypher/openCypher/blob/master/tools/tck-integrity-tests/src/test/scala/org/opencypher/tools/tck/ValidateSteps.scala#L110-L113


Bottom line: This PR can be merged.

2023-03-14 09:58 UTC, merged